name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: |
        uv venv
        uv sync --dev
    
    - name: Run tests
      run: |
        uv run pytest
    
    - name: Run linters
      run: |
        uv run ruff check src/
        uv run pylint src/